<h1>Broadcasting</h1>

In [ ]:
import numpy as np

In [ ]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [ ]:
my_3D_array.shape

(2, 7, 5)

In [ ]:
my_3D_array.ndim

3

In [ ]:
my_3D_array.size

70

In [ ]:
my_3D_array.dtype

dtype('int64')

In [ ]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

## Matrix multiplication

In [ ]:
left_mat = np.arange(6).reshape((2, 3))
right_mat = np.arange(15).reshape((5, 3))

In [ ]:
np.inner(left_mat, right_mat)

array([[  5,  14,  23,  32,  41],
       [ 14,  50,  86, 122, 158]])

In [ ]:
left_mat = np.arange(6).reshape((2, 3))
right_mat = np.arange(15).reshape((3, 5))

In [ ]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [ ]:
## Operations along axes

In [ ]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [ ]:
my_3D_array.shape

(2, 7, 5)

In [ ]:
my_3D_array.sum()

2415

In [ ]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [ ]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [ ]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [ ]:
## Broad Casting Rules

In [ ]:
my_2D_array = np.ones(35, dtype='int_').reshape((7,5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
my_random_2D_array = np.random.random((7,5))
my_random_2D_array

array([[0.6041, 0.4287, 0.9516, 0.2137, 0.9323],
       [0.7712, 0.2686, 0.9002, 0.5071, 0.7746],
       [0.7413, 0.5098, 0.5386, 0.6366, 0.8933],
       [0.3077, 0.7109, 0.21  , 0.956 , 0.4458],
       [0.5955, 0.1174, 0.3346, 0.1806, 0.4198],
       [0.9216, 0.5445, 0.0931, 0.1544, 0.7968],
       [0.4457, 0.0157, 0.753 , 0.9305, 0.0106]])

In [ ]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.4287,  1.9032,  0.641 ,  3.7291],
        [ 3.856 ,  1.6117,  6.3014,  4.0569,  6.9717],
        [ 7.4134,  5.6075,  6.4631,  8.2759, 12.5055],
        [ 4.6156, 11.3738,  3.5694, 17.2086,  8.4706],
        [11.9099,  2.465 ,  7.3622,  4.1534, 10.0745],
        [23.0396, 14.1575,  2.5143,  4.3221, 23.1081],
        [13.3704,  0.4881, 24.0945, 30.7051,  0.3616]],

       [[21.1448, 15.4338, 35.2091,  8.1191, 36.3584],
        [30.8479, 11.013 , 37.8083, 21.8059, 34.0839],
        [33.3601, 23.4493, 25.3138, 30.5573, 43.7693],
        [15.3854, 36.2539, 10.9183, 50.6699, 24.0744],
        [32.7521,  6.5734, 19.0747, 10.4737, 24.7665],
        [55.2951, 33.2157,  5.7735,  9.7246, 50.9972],
        [28.9691,  1.0391, 50.4479, 63.2712,  0.7339]]])

In [ ]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [ ]:
my_3D_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [ ]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])