# Joining and Splitting Arrays
- concatenate
- stack
- split


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
together.shape

(3, 2)

In [ ]:
together[1,1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
c = np.array([[1,2], [3,4]]) * 3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [ ]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [ ]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[ 0.30119103,  1.22931113, -0.17288605, -0.06422834],
        [-2.31920985, -2.35565622,  0.0859242 ,  1.34985822],
        [-1.17363221,  0.66044807,  1.89487144, -0.42507474]],

       [[ 2.09283171, -1.94114031, -0.56822199, -0.7210692 ],
        [ 0.46454003,  0.01049078,  1.40002393, -0.34290941],
        [-1.24420455, -0.71873411, -0.53645181, -1.5408989 ]],

       [[-0.29328528, -0.02340597, -2.12245824, -0.94179448],
        [ 0.1118837 , -1.00340538, -0.74336474, -0.11073095],
        [ 1.07640013,  1.87046363,  0.41130522,  0.15583431]],

       [[-0.56068966,  0.56679859, -0.66409626,  1.3017907 ],
        [-0.0366662 , -0.21871972,  0.12513691, -0.33849406],
        [ 0.74020192,  1.34712291, -0.20706244,  0.44768236]],

       [[-1.69570815,  3.07665554,  1.3432015 ,  0.87696027],
        [-0.30756467,  0.09262526, -1.4435126 , -0.32671563],
        [-0.28071831,  0.1387293 , -0.47945095, -0.3361199 ]]])

In [ ]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [ ]:
stack2

array([[[ 0.30119103,  2.09283171, -0.29328528, -0.56068966,
         -1.69570815],
        [ 1.22931113, -1.94114031, -0.02340597,  0.56679859,
          3.07665554],
        [-0.17288605, -0.56822199, -2.12245824, -0.66409626,
          1.3432015 ],
        [-0.06422834, -0.7210692 , -0.94179448,  1.3017907 ,
          0.87696027]],

       [[-2.31920985,  0.46454003,  0.1118837 , -0.0366662 ,
         -0.30756467],
        [-2.35565622,  0.01049078, -1.00340538, -0.21871972,
          0.09262526],
        [ 0.0859242 ,  1.40002393, -0.74336474,  0.12513691,
         -1.4435126 ],
        [ 1.34985822, -0.34290941, -0.11073095, -0.33849406,
         -0.32671563]],

       [[-1.17363221, -1.24420455,  1.07640013,  0.74020192,
         -0.28071831],
        [ 0.66044807, -0.71873411,  1.87046363,  1.34712291,
          0.1387293 ],
        [ 1.89487144, -0.53645181,  0.41130522, -0.20706244,
         -0.47945095],
        [-0.42507474, -1.5408989 ,  0.15583431,  0.44768236,
         -0

In [ ]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

array([[5, 3, 4],
       [3, 5, 4],
       [3, 4, 5]])

In [ ]:
temp = np.arange(5)
temp


array([0, 1, 2, 3, 4])

In [ ]:
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [ ]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [ ]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[ 0.30119103,  1.22931113, -0.17288605, -0.06422834],
         [-2.31920985, -2.35565622,  0.0859242 ,  1.34985822],
         [-1.17363221,  0.66044807,  1.89487144, -0.42507474]]]),
 array([[[ 2.09283171, -1.94114031, -0.56822199, -0.7210692 ],
         [ 0.46454003,  0.01049078,  1.40002393, -0.34290941],
         [-1.24420455, -0.71873411, -0.53645181, -1.5408989 ]]]),
 array([[[-0.29328528, -0.02340597, -2.12245824, -0.94179448],
         [ 0.1118837 , -1.00340538, -0.74336474, -0.11073095],
         [ 1.07640013,  1.87046363,  0.41130522,  0.15583431]]]),
 array([[[-0.56068966,  0.56679859, -0.66409626,  1.3017907 ],
         [-0.0366662 , -0.21871972,  0.12513691, -0.33849406],
         [ 0.74020192,  1.34712291, -0.20706244,  0.44768236]]]),
 array([[[-1.69570815,  3.07665554,  1.3432015 ,  0.87696027],
         [-0.30756467,  0.09262526, -1.4435126 , -0.32671563],
         [-0.28071831,  0.1387293 , -0.47945095, -0.3361199 ]]])]

In [ ]:
type(s0)

list

In [ ]:
s0[2]

array([[[-0.29328528, -0.02340597, -2.12245824, -0.94179448],
        [ 0.1118837 , -1.00340538, -0.74336474, -0.11073095],
        [ 1.07640013,  1.87046363,  0.41130522,  0.15583431]]])

In [ ]:
s0[2]

array([[[-0.29328528, -0.02340597, -2.12245824, -0.94179448],
        [ 0.1118837 , -1.00340538, -0.74336474, -0.11073095],
        [ 1.07640013,  1.87046363,  0.41130522,  0.15583431]]])

In [ ]:
s0[2].shape

(1, 3, 4)

In [ ]:
s1=np.split (before_split, 3, axis=1)
s1

[array([[[ 0.30119103,  1.22931113, -0.17288605, -0.06422834]],
 
        [[ 2.09283171, -1.94114031, -0.56822199, -0.7210692 ]],
 
        [[-0.29328528, -0.02340597, -2.12245824, -0.94179448]],
 
        [[-0.56068966,  0.56679859, -0.66409626,  1.3017907 ]],
 
        [[-1.69570815,  3.07665554,  1.3432015 ,  0.87696027]]]),
 array([[[-2.31920985, -2.35565622,  0.0859242 ,  1.34985822]],
 
        [[ 0.46454003,  0.01049078,  1.40002393, -0.34290941]],
 
        [[ 0.1118837 , -1.00340538, -0.74336474, -0.11073095]],
 
        [[-0.0366662 , -0.21871972,  0.12513691, -0.33849406]],
 
        [[-0.30756467,  0.09262526, -1.4435126 , -0.32671563]]]),
 array([[[-1.17363221,  0.66044807,  1.89487144, -0.42507474]],
 
        [[-1.24420455, -0.71873411, -0.53645181, -1.5408989 ]],
 
        [[ 1.07640013,  1.87046363,  0.41130522,  0.15583431]],
 
        [[ 0.74020192,  1.34712291, -0.20706244,  0.44768236]],
 
        [[-0.28071831,  0.1387293 , -0.47945095, -0.3361199 ]]])]

In [ ]:
s2=np.split (before_split, 4, axis=2)
s2

[array([[[ 0.30119103],
         [-2.31920985],
         [-1.17363221]],
 
        [[ 2.09283171],
         [ 0.46454003],
         [-1.24420455]],
 
        [[-0.29328528],
         [ 0.1118837 ],
         [ 1.07640013]],
 
        [[-0.56068966],
         [-0.0366662 ],
         [ 0.74020192]],
 
        [[-1.69570815],
         [-0.30756467],
         [-0.28071831]]]),
 array([[[ 1.22931113],
         [-2.35565622],
         [ 0.66044807]],
 
        [[-1.94114031],
         [ 0.01049078],
         [-0.71873411]],
 
        [[-0.02340597],
         [-1.00340538],
         [ 1.87046363]],
 
        [[ 0.56679859],
         [-0.21871972],
         [ 1.34712291]],
 
        [[ 3.07665554],
         [ 0.09262526],
         [ 0.1387293 ]]]),
 array([[[-0.17288605],
         [ 0.0859242 ],
         [ 1.89487144]],
 
        [[-0.56822199],
         [ 1.40002393],
         [-0.53645181]],
 
        [[-2.12245824],
         [-0.74336474],
         [ 0.41130522]],
 
        [[-0.66409626],
 