# Joining and Splitting arrays
- concatenate
- stack
- split

In [2]:
import numpy as np

### concatenate
documentation: http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [25]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
together.shape

(3, 2)

In [27]:
together[1,1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [28]:
a

array([[1, 2],
       [3, 4]])

In [29]:
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [30]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

### stack

In [8]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[-1.18221033,  0.8794368 ,  1.04397402,  1.54248418],
        [ 2.15517292, -0.41590548, -0.47411981, -0.85446468],
        [-0.5467576 , -0.17805295,  0.74718373, -0.85918489]],

       [[ 0.99922629,  2.2266379 , -1.03527259,  1.31458375],
        [-2.13968804, -0.39433587,  1.71506755, -0.54819918],
        [-0.56628347, -0.14802366,  0.97525552, -0.631596  ]],

       [[ 0.78194832, -2.27149732, -1.02808947, -0.84738016],
        [-0.94530794, -0.77319444,  0.01623713,  0.01696452],
        [-1.19166104, -0.13689586, -0.62050553,  0.31720613]],

       [[ 0.42296136,  0.25482976, -1.29466026, -0.57394076],
        [ 0.18391996, -0.86602827,  2.73949112,  1.38112453],
        [-0.42725916, -1.35284525, -0.04967307, -0.67863503]],

       [[-0.49544948, -0.14912159, -0.57017557, -0.1209654 ],
        [ 0.77243958, -0.50037615, -0.51223141, -0.1295934 ],
        [ 1.34420523,  0.91983239, -0.76750917,  0.40602833]]])

In [32]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [33]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

array([[5, 3, 4],
       [3, 5, 4],
       [3, 4, 5]])

In [34]:
stack0

array([[[-1.67111666, -1.77312429, -0.11157658,  0.57131703],
        [ 1.08374805,  0.34744236,  0.10991829,  1.30350911],
        [-0.52289443, -1.21957339, -0.2035887 ,  0.31155047]],

       [[-0.99252035,  0.62318867,  0.63820547,  0.07638464],
        [-0.44640297, -1.90686092,  0.44524353,  2.07716712],
        [-0.86492952, -0.91818943, -0.03095393, -0.58845213]],

       [[-1.23813727,  0.47647202,  2.16335874, -2.67905092],
        [ 0.86685027,  1.00761015, -0.75155321, -0.75433504],
        [-0.90589979, -0.8594017 , -1.75478817, -0.89139958]],

       [[ 0.74364534,  0.21782878,  0.08451976, -1.18676986],
        [ 0.54047173,  1.06346904,  0.91173701, -0.69110582],
        [ 0.77735808, -1.51785954,  0.2303225 ,  0.67743367]],

       [[ 1.25709492,  0.66662648,  0.62396185,  0.18064289],
        [ 0.0439015 ,  1.48259207, -0.65545813,  1.97419587],
        [ 0.12000067, -1.29599458, -1.25730427,  0.15815604]]])

In [35]:
stack1

array([[[-1.67111666, -1.77312429, -0.11157658,  0.57131703],
        [-0.99252035,  0.62318867,  0.63820547,  0.07638464],
        [-1.23813727,  0.47647202,  2.16335874, -2.67905092],
        [ 0.74364534,  0.21782878,  0.08451976, -1.18676986],
        [ 1.25709492,  0.66662648,  0.62396185,  0.18064289]],

       [[ 1.08374805,  0.34744236,  0.10991829,  1.30350911],
        [-0.44640297, -1.90686092,  0.44524353,  2.07716712],
        [ 0.86685027,  1.00761015, -0.75155321, -0.75433504],
        [ 0.54047173,  1.06346904,  0.91173701, -0.69110582],
        [ 0.0439015 ,  1.48259207, -0.65545813,  1.97419587]],

       [[-0.52289443, -1.21957339, -0.2035887 ,  0.31155047],
        [-0.86492952, -0.91818943, -0.03095393, -0.58845213],
        [-0.90589979, -0.8594017 , -1.75478817, -0.89139958],
        [ 0.77735808, -1.51785954,  0.2303225 ,  0.67743367],
        [ 0.12000067, -1.29599458, -1.25730427,  0.15815604]]])

In [36]:
stack2

array([[[-1.67111666, -0.99252035, -1.23813727,  0.74364534,  1.25709492],
        [-1.77312429,  0.62318867,  0.47647202,  0.21782878,  0.66662648],
        [-0.11157658,  0.63820547,  2.16335874,  0.08451976,  0.62396185],
        [ 0.57131703,  0.07638464, -2.67905092, -1.18676986,  0.18064289]],

       [[ 1.08374805, -0.44640297,  0.86685027,  0.54047173,  0.0439015 ],
        [ 0.34744236, -1.90686092,  1.00761015,  1.06346904,  1.48259207],
        [ 0.10991829,  0.44524353, -0.75155321,  0.91173701, -0.65545813],
        [ 1.30350911,  2.07716712, -0.75433504, -0.69110582,  1.97419587]],

       [[-0.52289443, -0.86492952, -0.90589979,  0.77735808,  0.12000067],
        [-1.21957339, -0.91818943, -0.8594017 , -1.51785954, -1.29599458],
        [-0.2035887 , -0.03095393, -1.75478817,  0.2303225 , -1.25730427],
        [ 0.31155047, -0.58845213, -0.89139958,  0.67743367,  0.15815604]]])

### split
for information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

In [50]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [37]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [38]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[-1.67111666, -1.77312429, -0.11157658,  0.57131703],
         [ 1.08374805,  0.34744236,  0.10991829,  1.30350911],
         [-0.52289443, -1.21957339, -0.2035887 ,  0.31155047]]]),
 array([[[-0.99252035,  0.62318867,  0.63820547,  0.07638464],
         [-0.44640297, -1.90686092,  0.44524353,  2.07716712],
         [-0.86492952, -0.91818943, -0.03095393, -0.58845213]]]),
 array([[[-1.23813727,  0.47647202,  2.16335874, -2.67905092],
         [ 0.86685027,  1.00761015, -0.75155321, -0.75433504],
         [-0.90589979, -0.8594017 , -1.75478817, -0.89139958]]]),
 array([[[ 0.74364534,  0.21782878,  0.08451976, -1.18676986],
         [ 0.54047173,  1.06346904,  0.91173701, -0.69110582],
         [ 0.77735808, -1.51785954,  0.2303225 ,  0.67743367]]]),
 array([[[ 1.25709492,  0.66662648,  0.62396185,  0.18064289],
         [ 0.0439015 ,  1.48259207, -0.65545813,  1.97419587],
         [ 0.12000067, -1.29599458, -1.25730427,  0.15815604]]])]

In [39]:
type(s0)

list

In [54]:
s0[1]

array([[[-0.99252035,  0.62318867,  0.63820547,  0.07638464],
        [-0.44640297, -1.90686092,  0.44524353,  2.07716712],
        [-0.86492952, -0.91818943, -0.03095393, -0.58845213]]])

In [55]:
s0[1].shape

(1, 3, 4)

In [41]:
s1=np.split (before_split, 3, axis=1)
s1

[array([[[-1.67111666, -1.77312429, -0.11157658,  0.57131703]],
 
        [[-0.99252035,  0.62318867,  0.63820547,  0.07638464]],
 
        [[-1.23813727,  0.47647202,  2.16335874, -2.67905092]],
 
        [[ 0.74364534,  0.21782878,  0.08451976, -1.18676986]],
 
        [[ 1.25709492,  0.66662648,  0.62396185,  0.18064289]]]),
 array([[[ 1.08374805,  0.34744236,  0.10991829,  1.30350911]],
 
        [[-0.44640297, -1.90686092,  0.44524353,  2.07716712]],
 
        [[ 0.86685027,  1.00761015, -0.75155321, -0.75433504]],
 
        [[ 0.54047173,  1.06346904,  0.91173701, -0.69110582]],
 
        [[ 0.0439015 ,  1.48259207, -0.65545813,  1.97419587]]]),
 array([[[-0.52289443, -1.21957339, -0.2035887 ,  0.31155047]],
 
        [[-0.86492952, -0.91818943, -0.03095393, -0.58845213]],
 
        [[-0.90589979, -0.8594017 , -1.75478817, -0.89139958]],
 
        [[ 0.77735808, -1.51785954,  0.2303225 ,  0.67743367]],
 
        [[ 0.12000067, -1.29599458, -1.25730427,  0.15815604]]])]

In [43]:
s2=np.split (before_split, 4, axis=2)
s2

[array([[[-1.67111666],
         [ 1.08374805],
         [-0.52289443]],
 
        [[-0.99252035],
         [-0.44640297],
         [-0.86492952]],
 
        [[-1.23813727],
         [ 0.86685027],
         [-0.90589979]],
 
        [[ 0.74364534],
         [ 0.54047173],
         [ 0.77735808]],
 
        [[ 1.25709492],
         [ 0.0439015 ],
         [ 0.12000067]]]), array([[[-1.77312429],
         [ 0.34744236],
         [-1.21957339]],
 
        [[ 0.62318867],
         [-1.90686092],
         [-0.91818943]],
 
        [[ 0.47647202],
         [ 1.00761015],
         [-0.8594017 ]],
 
        [[ 0.21782878],
         [ 1.06346904],
         [-1.51785954]],
 
        [[ 0.66662648],
         [ 1.48259207],
         [-1.29599458]]]), array([[[-0.11157658],
         [ 0.10991829],
         [-0.2035887 ]],
 
        [[ 0.63820547],
         [ 0.44524353],
         [-0.03095393]],
 
        [[ 2.16335874],
         [-0.75155321],
         [-1.75478817]],
 
        [[ 0.08451976],
   