<h1>Slicing Arrays</h1>

In [1]:
import numpy as np 

In [2]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [3]:
my_vector[2]

0

In [4]:
my_vector[0] = -102
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [5]:
305 % 7

4

In [7]:
try:
    print(my_vector[305])
except:
    print(my_vector[305 % 7])

21


In [8]:
my_vector.size

7

In [10]:
my_array = np.arange(35)
my_array.shape = (7, 5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [11]:
my_array[2]

array([10, 11, 12, 13, 14])

In [13]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [14]:
my_array[5,2]

27

In [16]:
row, column = 5, 2
my_array[row, column]


27

In [17]:
my_array[5][2]

27

In [19]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2, 5, 7)
my_3D_array

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

In [20]:
my_3D_array[1]

array([[35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69]])

In [21]:
my_3D_array[1, 3]

array([56, 57, 58, 59, 60, 61, 62])

In [22]:
my_3D_array[1,2, 3] = 1111
my_3D_array

array([[[   0,    1,    2,    3,    4,    5,    6],
        [   7,    8,    9,   10,   11,   12,   13],
        [  14,   15,   16,   17,   18,   19,   20],
        [  21,   22,   23,   24,   25,   26,   27],
        [  28,   29,   30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39,   40,   41],
        [  42,   43,   44,   45,   46,   47,   48],
        [  49,   50,   51, 1111,   53,   54,   55],
        [  56,   57,   58,   59,   60,   61,   62],
        [  63,   64,   65,   66,   67,   68,   69]]])

In [28]:
my_3D_array[: , : , 1]

array([[ 1,  8, 15, 22, 29],
       [36, 43, 50, 57, 64]])

In [30]:
my_3D_array[: , : , :2]

array([[[ 0,  1],
        [ 7,  8],
        [14, 15],
        [21, 22],
        [28, 29]],

       [[35, 36],
        [42, 43],
        [49, 50],
        [56, 57],
        [63, 64]]])