Pandas exercises from https://www.machinelearningplus.com/python/101-pandas-exercises-python/.

## Exercise 34

How to change column values when importing csv to a dataframe.
Using th Boston housing dataset and changing the value of medv(medium houses value) to 'low' for values smaller 25 and 'hihg' for values > 25.

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', 
                converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

print(df)

         crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   
1     0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242   
2     0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242   
3     0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222   
4     0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222   
5     0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222   
6     0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311   
7     0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311   
8     0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311   
9     0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311   
10    0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311   
11    0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311   
12    0.09378  12.5   7.8

## Exercise 35
How to create a dataframe with rows as strides from a give series

In [2]:
# Input
ser_L = pd.Series(range(16))
print(ser_L)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
dtype: int64


In [3]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

ser_reshape = gen_strides(ser_L, stride_len=2, window_len=4)
print(ser_reshape)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14 15]]


## Exercise 36
How to import only specified columns from a csv file
Import only crim and medv columns from the boston housing data set as a dataframe

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df)

         crim  medv
0     0.00632  24.0
1     0.02731  21.6
2     0.02729  34.7
3     0.03237  33.4
4     0.06905  36.2
5     0.02985  28.7
6     0.08829  22.9
7     0.14455  27.1
8     0.21124  16.5
9     0.17004  18.9
10    0.22489  15.0
11    0.11747  18.9
12    0.09378  21.7
13    0.62976  20.4
14    0.63796  18.2
15    0.62739  19.9
16    1.05393  23.1
17    0.78420  17.5
18    0.80271  20.2
19    0.72580  18.2
20    1.25179  13.6
21    0.85204  19.6
22    1.23247  15.2
23    0.98843  14.5
24    0.75026  15.6
25    0.84054  13.9
26    0.67191  16.6
27    0.95577  14.8
28    0.77299  18.4
29    1.00245  21.0
..        ...   ...
476   4.87141  16.7
477  15.02340  12.0
478  10.23300  14.6
479  14.33370  21.4
480   5.82401  23.0
481   5.70818  23.7
482   5.73116  25.0
483   2.81838  21.8
484   2.37857  20.6
485   3.67367  21.2
486   5.69175  19.1
487   4.83567  20.6
488   0.15086  15.2
489   0.18337   7.0
490   0.20746   8.1
491   0.10574  13.6
492   0.11132  20.1
493   0.17331  21.8


## Exercise 37
How to get the nrows, ncolumns, datatype and and summary stats of each column of a DataFrame
Get these statistics from the cars93 dataset.

In [5]:
df_cars93 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df_cars93.head())

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

In [6]:
# number of rows and columns
print(df_cars93.shape)

(93, 27)


In [7]:
# how many columns under each datatype
print(df_cars93.get_dtype_counts())

float64    18
object      9
dtype: int64


In [8]:
# same information with other functions
print(df_cars93.dtypes.value_counts())

float64    18
object      9
dtype: int64


In [9]:
# and now the summary statistics
df_cars93.describe()

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

In [10]:
#convert dataframe to numpy array
df_cars93_arr = df_cars93.values
print(df_cars93_arr)

[['Acura' 'Integra' 'Small' ... 2705.0 'non-USA' 'Acura Integra']
 [nan 'Legend' 'Midsize' ... 3560.0 'non-USA' 'Acura Legend']
 ['Audi' '90' 'Compact' ... 3375.0 'non-USA' 'Audi 90']
 ...
 ['Volkswagen' 'Corrado' 'Sporty' ... 2810.0 'non-USA'
  'Volkswagen Corrado']
 ['Volvo' '240' 'Compact' ... 2985.0 'non-USA' 'Volvo 240']
 [nan '850' 'Midsize' ... 3245.0 'non-USA' 'Volvo 850']]


In [11]:
#convert dataframe to list
df_cars93_list = df_cars93.values.tolist()
print(df_cars93_list)

[['Acura', 'Integra', 'Small', 12.9, 15.9, 18.8, 25.0, 31.0, 'None', 'Front', '4', 1.8, 140.0, 6300.0, 2890.0, 'Yes', 13.2, 5.0, 177.0, 102.0, 68.0, 37.0, 26.5, nan, 2705.0, 'non-USA', 'Acura Integra'], [nan, 'Legend', 'Midsize', 29.2, 33.9, 38.7, 18.0, 25.0, 'Driver & Passenger', 'Front', '6', 3.2, 200.0, 5500.0, 2335.0, 'Yes', 18.0, 5.0, 195.0, 115.0, 71.0, 38.0, 30.0, 15.0, 3560.0, 'non-USA', 'Acura Legend'], ['Audi', '90', 'Compact', 25.9, 29.1, 32.3, 20.0, 26.0, 'Driver only', 'Front', '6', 2.8, 172.0, 5500.0, 2280.0, 'Yes', 16.9, 5.0, 180.0, 102.0, 67.0, 37.0, 28.0, 14.0, 3375.0, 'non-USA', 'Audi 90'], ['Audi', '100', 'Midsize', nan, 37.7, 44.6, 19.0, 26.0, 'Driver & Passenger', nan, '6', nan, 172.0, 5500.0, 2535.0, nan, 21.1, 6.0, 193.0, 106.0, nan, 37.0, 31.0, 17.0, 3405.0, 'non-USA', 'Audi 100'], ['BMW', '535i', 'Midsize', nan, 30.0, nan, 22.0, 30.0, nan, 'Rear', '4', 3.5, 208.0, 5700.0, 2545.0, 'Yes', 21.1, 4.0, 186.0, 109.0, 69.0, 39.0, 27.0, 13.0, 3640.0, 'non-USA', 'BMW 53

## Exercise 38
How to extract the row and column number of a cell with a given criterion?
Which manufacturer, model and tpye has the highest price value?

In [12]:
df_cars93 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df_cars93.head())

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

In [13]:
# Get Manufacturuer, Model, Type of the most expensive car
df_cars93.loc[df_cars93.Price == np.max(df_cars93.Price), ['Manufacturer', 'Model', 'Type' ]]

Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize

In [14]:
# Get the row and column of this car

row, column = np.where(df_cars93.values == np.max(df_cars93.Price) )
print( row, column)

[58] [4]


In [15]:
# Get the price of this car . here we offer solutions 1 an 2
result1 = df_cars93.iat[row[0], column[0]]
result2 = df_cars93.iloc[row[0], column[0]]

In [16]:
result3 = df_cars93.at[row[0], 'Price']
result4 = df_cars93.get_value(row[0], 'Price')

c:\users\d022785\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  


In [17]:
print('result1: ', result1)
print('result2: ', result2)
print('result3: ', result3)
print('result4: ', result4)

result1:  61.9
result2:  61.9
result3:  61.9
result4:  61.9


## Exercise 39
How to rename a specific column in a dataframe

Rename the column 'Type' to 'CarType' and replace the '.' in all column names by '_'

In [18]:
df_cars93 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df_cars93.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [19]:
df_cars93 = df_cars93.rename(columns = {'Type': 'CarTypp'})

In [20]:
print(df_cars93.columns)

Index(['Manufacturer', 'Model', 'CarTypp', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [21]:
df_cars93.columns.values[2] = 'CarType'
print(df_cars93.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [22]:
# Now replace all dots by underlines

df_cars93.columns = df_cars93.columns.map(lambda x: x.replace('.', '_'))
print(df_cars93.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Exercise 40
How to check if a dataframe has missing values

In [23]:
df_cars93.isnull().values.any()

True

## Exercise 41
now we want to count the number of empty values in each column

In [24]:
n_missings_each_column = df_cars93.apply(lambda x: x.isnull().sum())
print(n_missings_each_column)
n_missings_each_column.argmax()

Manufacturer           4
Model                  1
CarType                3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64


c:\users\d022785\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  This is separate from the ipykernel package so we can avoid doing imports until


'Luggage_room'

## Exercise 42
Replace empty values with the mean value.
Fill the Min.Price and Max.Price with the mean value

In [25]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out)

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
5   14.200000  17.300000
6   19.900000  21.459091
7   22.600000  24.900000
8   26.300000  26.300000
9   33.000000  36.300000
10  37.500000  42.700000
11   8.500000  18.300000
12  11.400000  11.400000
13  13.400000  16.800000
14  13.400000  18.400000
15  14.700000  18.000000
16  14.700000  18.600000
17  18.000000  19.600000
18  34.600000  41.500000
19  18.400000  18.400000
20  14.500000  17.100000
21  29.500000  29.500000
22   7.900000  10.600000
23   8.400000  14.200000
24  11.900000  14.700000
25  17.118605  24.400000
26  14.800000  16.400000
27  18.500000  33.100000
28   7.900000  16.500000
29  17.118605  21.200000
..        ...        ...
63   8.700000  14.900000
64  13.000000  18.300000
65  16.700000  21.500000
66  21.000000  22.000000
67  13.000000  14.000000
68  14.200000  18.400000
69  19.500000  19.500000
70  19.500000  21.900000


In [26]:
print(df.Price.mean())

19.61648351648352


Comment: for the fields with a '.' in the name the command df.<field_with_dot>.mean() does not work as the dot is interpreted as the end of a field name and then any function is expected. Therefore I will rename those 2 fields

In [27]:
df_new = df.rename(columns = {'Min.Price': 'Min_Price', 'Max.Price': 'Max_Price'})

In [28]:
print(df_new.Min_Price.mean())

17.11860465116279


In [29]:
print(df_new.Max_Price.mean())

21.45909090909091


## Exercise 43
How to use the 'apply' function on existing columns with global variables as additional arguments

In [30]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
# print(df)
df_new = df.rename(columns = {'Min.Price': 'Min_Price', 'Max.Price': 'Max_Price'})
print(df_new)

   Manufacturer          Model     Type  Min_Price  Price  Max_Price  \
0         Acura        Integra    Small  12.900000   15.9      18.80   
1           NaN         Legend  Midsize  29.200000   33.9      38.70   
2          Audi             90  Compact  25.900000   29.1      32.30   
3          Audi            100  Midsize  17.118605   37.7      44.60   
4           BMW           535i  Midsize  17.118605   30.0      19.15   
5         Buick        Century  Midsize  14.200000   15.7      17.30   
6         Buick        LeSabre    Large  19.900000   20.8      19.15   
7         Buick     Roadmaster    Large  22.600000   23.7      24.90   
8         Buick        Riviera  Midsize  26.300000   26.3      26.30   
9      Cadillac        DeVille    Large  33.000000   34.7      36.30   
10     Cadillac        Seville  Midsize  37.500000   40.1      42.70   
11    Chevrolet       Cavalier  Compact   8.500000   13.4      18.30   
12    Chevrolet        Corsica  Compact  11.400000   11.4      1

In [31]:
print(np.nanmean, np.nanmedian)

<function nanmean at 0x0000020E89FB6730> <function nanmedian at 0x0000020E89FB69D8>


In [32]:
df_new.Min_Price.mean()

17.11860465116279

In [33]:
df_new.Max_Price.median()

19.15

In [34]:
df_new.Max_Price.mean()

21.33494623655914

## Exercise 44
How to select a specificcolumn from a dataframe as a dataframe instead of a series.
Get the first column (a) in df as a dataframe (rather than the series)

In [35]:
df_44 = pd.DataFrame(np.arange(30).reshape(-1, 5), columns = list('abcde'))
print(df_44)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29


In [36]:
print(type(df_44.a))
print(type(df_44['a']))
print(df_44['a'])

# 2 Anotationen

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
0     0
1     5
2    10
3    15
4    20
5    25
Name: a, dtype: int32


In [37]:
print(type(df_44.loc[:, ['a']]))
print(df_44.loc[:, ['a']])

<class 'pandas.core.frame.DataFrame'>
    a
0   0
1   5
2  10
3  15
4  20
5  25


In [38]:
print(type(df_44.iloc[:, [0]]))
df_44.iloc[:, [0]]

<class 'pandas.core.frame.DataFrame'>


a
0   0
1   5
2  10
3  15
4  20
5  25

In [39]:
# Alternately the following returns a Series
print(type(df_44.a))
print(type(df_44['a']))
print(type(df_44.loc[:, 'a']))
print(type(df_44.iloc[:, 1]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [40]:
# Alternately the following returns a Series
print(df_44.a)
print(df_44['a'])
print(df_44.loc[:, 'a'])
print(df_44.iloc[:, 1])

0     0
1     5
2    10
3    15
4    20
5    25
Name: a, dtype: int32
0     0
1     5
2    10
3    15
4    20
5    25
Name: a, dtype: int32
0     0
1     5
2    10
3    15
4    20
5    25
Name: a, dtype: int32
0     1
1     6
2    11
3    16
4    21
5    26
Name: b, dtype: int32


## Exercise 45
How to change the order of columns within a DataFrame
1.) Change columns a and c 
2.) Create generic function to interchange 2 columns without hardcoding the column names
3.) Sort the columns in reverse alphabetical order meaning 'e' first and 'a' the last

In [41]:
df_45 = pd.DataFrame(np.arange(40).reshape(-1, 5), columns=list('abcde'))
print(df_45)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39


In [42]:
df_45[list('cbade')]

c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
4  22  21  20  23  24
5  27  26  25  28  29
6  32  31  30  33  34
7  37  36  35  38  39

In [43]:
df_45 = pd.DataFrame(np.arange(40).reshape(-1, 5), columns=list('abcde'))

def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df_45a = switch_columns(df_45, 'a', 'c')
print(df_45a)

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
4  22  21  20  23  24
5  27  26  25  28  29
6  32  31  30  33  34
7  37  36  35  38  39


In [44]:
df_45_sorted = df_45[sorted(df_45.columns)]
print(df_45_sorted)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39


In [45]:
df_45_sorted2 = df_45.sort_index(axis=1, ascending = False, inplace=False)

In [47]:
print(df_45)
print(df_45_sorted2)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29
6  30  31  32  33  34
7  35  36  37  38  39
    e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15
4  24  23  22  21  20
5  29  28  27  26  25
6  34  33  32  31  30
7  39  38  37  36  35


## Exercise 46
How to set the number of rows and columns displayed in the output?
Show at max 10 rows and 10 columns

In [48]:
df_46 = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv")

In [51]:
# Solution
pd.set_option('display.max_columns', 14)
pd.set_option('display.max_rows', 8)
# df

# Show all available options
# pd.describe_option()

df_46

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  ...  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0  ...   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0  ...   
2          Audi       90  Compact       25.9   29.1       32.3      20.0  ...   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0  ...   
..          ...      ...      ...        ...    ...        ...       ...  ...   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0  ...   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0  ...   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0  ...   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0  ...   

    Width Turn.circle Rear.seat.room Luggage.room  Weight   Origin  \
0    68.0        37.0           26.5          NaN  2705.0  non-USA   
1    71.0        38.0           30.0         15.0  3560.0  non-USA   
2    67.0        37.0           28.0         14.0  3375.0  non-USA   
3     NaN        37.0           31.0         17.0  3405.0  non-USA   
..    ...         ...            ...          ...     ...      ...   
89   67.0        35.0           31.5         14.0  2985.0  non-USA   
90   66.0        36.0           26.0         15.0  2810.0  non-USA   
91   67.0        37.0           29.5         14.0  2985.0  non-USA   
92   69.0        38.0           30.0         15.0  3245.0  non-USA   

                  Make  
0        Acura Integra  
1         Acura Legend  
2              Audi 90  
3             Audi 100  
..                 ...  
89   Volkswagen Passat  
90  Volkswagen Corrado  
91           Volvo 240  
92           Volvo 850  

[93 rows x 27 columns]

## Exercise 47

How to format or suppress scientific notations in a pandas dataframe?
suppress scientific notations like ‘e-03’ in df and print upto 4 numbers after decimal.

df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df
#>          random
#> 0  3.474280e-03
#> 1  3.951517e-05
#> 2  7.469702e-02
#> 3  5.541282e-28

Desired Output

#>    random
#> 0  0.0035
#> 1  0.0000
#> 2  0.0747
#> 3  0.0000

In [52]:
df_47 = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df_47

random
0  3.716159e-02
1  2.093805e-21
2  1.106730e-01
3  4.607573e-01

In [53]:
# Solution 1: Rounding
df_47.round(4)

random
0  0.0372
1  0.0000
2  0.1107
3  0.4608

In [56]:
# Solution 2: Use apply to change format
df_47.apply(lambda x: '%.4f' % x, axis=1)
# or
df_47.applymap(lambda x: '%.4f' % x)


random
0  0.0372
1  0.0000
2  0.1107
3  0.4608

In [57]:
# Solution 3: Use set_option
pd.set_option('display.float_format', lambda x: '%.4f' % x)
df_47

random
0  0.0372
1  0.0000
2  0.1107
3  0.4608

In [59]:
# Solution 4: Assign display.float_format
pd.options.display.float_format = '{:.4f}'.format
print(df_47)

# Reset/undo float formatting
pd.options.display.float_format = None

   random
0  0.0372
1  0.0000
2  0.1107
3  0.4608


## Exercise 48 

How to format all the values in a dataframe as percentages?

Difficulty Level: L2

Format the values in column 'random' of df as percentages.

Input

df = pd.DataFrame(np.random.random(4), columns=['random'])

In [61]:
df_48 = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df_48.style.format({
    'random': '{0:.2%}'.format,
})

out

## Exercise 49

How to filter every nth row in a dataframe?

Difficulty Level: L1

From df, filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [62]:
df_49 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df_49.iloc[2::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer     Model     Type
2          Audi        90  Compact
22        Dodge      Colt    Small
42        Honda    Accord  Compact
62   Mitsubishi  Diamante  Midsize
82       Suzuki     Swift      NaN


## Exercise 50

How to create a primary key index by combining relevant columns?

Difficulty Level: L2

In df, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and 'Type' and create a index as a combination of these three columns and check if the index is a primary key.

Input

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

In [63]:
df_50 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df_50[['Manufacturer', 'Model', 'Type']] = df_50[['Manufacturer', 'Model', 'Type']].fillna('missing')
df_50.index = df_50.Manufacturer + '_' + df_50.Model + '_' + df_50.Type
print(df_50.index.is_unique)
print(df_50)

True
                          Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small              Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize         missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                   Audi       90  Compact       25.9       32.3
Audi_100_Midsize                  Audi      100  Midsize        NaN       44.6
...                                ...      ...      ...        ...        ...
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6       22.4
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9       23.7
Volvo_240_Compact                Volvo      240  Compact       21.8       23.5
missing_850_Midsize            missing      850  Midsize       24.8       28.5

[93 rows x 5 columns]
