# Views and Copies

In [ ]:
import numpy as np

In [ ]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [ ]:
su_casa = mi_casa

### Same or Different?

In [ ]:
#reference equality
mi_casa is su_casa

True

In [ ]:
id(mi_casa)

139944664533872

In [ ]:
id(su_casa)

139944664533872

In [ ]:
#value inequality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
su_casa[4] = 1010

In [ ]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [ ]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [ ]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [ ]:
tree_house = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [ ]:
tree_house == mi_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [ ]:
id(tree_house)

139943587246608

In [ ]:
id(mi_casa)

139944664533872

In [ ]:
tree_house[0] = 214

In [ ]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [ ]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [ ]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [ ]:
tree_house is mi_casa

False

## View: a shallow copy

In [ ]:
farm_house = tree_house.view()
farm_house.shape = (2,4)

In [ ]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [ ]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [ ]:
tree_house [3] = -111

In [ ]:
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

## Deep Copy


In [ ]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [ ]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])