<h1>Linear Algebra</h1>

In [36]:
import numpy as np

In [37]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [38]:
# transpose
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [39]:
# matrix inverse
my_first_inverse = my_first_matrix.I
my_first_inverse

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [40]:
#should return inverse; floating point values "almost" equal zero
my_first_matrix * my_first_inverse

matrix([[ 1.,  0.,  0.],
        [-0.,  1.,  0.],
        [ 0., -0.,  1.]])

In [41]:
# create an identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### Solve simultaneous linear equations

In [42]:
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

In [43]:
# not efficient; use only for small matrices
solution = my_first_inverse * right_hand_side
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [44]:
# confirm that solution is correct
my_first_matrix * solution - right_hand_side

matrix([[ 0.],
        [ 0.],
        [ 0.]])

In [45]:
# more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix, right_hand_side)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [47]:
# Compute the eigenvalues and right eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

(array([ 13.08576474,   2.58000566,  -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))