<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [2]:
import numpy as np

In [6]:
np.linspace(5, 15, 11)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

In [10]:
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace[1]

1.25

In [11]:
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [12]:
my_linspace[0]

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [13]:
my_linspace[1]

1.25

In [14]:
type(my_linspace)

tuple

In [15]:
len(my_linspace)

2

<h2>Zeros< amd Ones/h2>

In [17]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.zeros(7) + 1

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.zeros( (5, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
np.zeros(11, dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])